# Generated by Django 3.1.1 on 2021-06-20 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=120, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('work_phone_number', models.CharField(blank=True, max_length=15)),
                ('telegram_id', models.CharField(blank=True, max_length=60)),
                ('instagram_id', models.CharField(blank=True, max_length=60)),
                ('telegram_phone_number', models.CharField(blank=True, max_length=60)),
                ('whatsapp_phone_number', models.CharField(blank=True, max_length=60)),
                ('website', models.URLField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('create_account_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('accounting_codes', models.TextField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(auto_now=True, null=True)),
                ('picture', models.FileField(blank=True, upload_to='media/%Y-%m-%d')),
                ('institution', models.CharField(blank=True, max_length=70)),
                ('department', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('skype', models.CharField(blank=True, max_length=50)),
                ('yahoo', models.CharField(blank=True, max_length=70)),
                ('first_access', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_access', models.DateTimeField(auto_now=True, null=True)),
                ('policy_agreed', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('permission', models.ManyToManyField(related_name='users', to='auth.Permission')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
