# Generated by Django 3.1.1 on 2021-06-22 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20210621_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveField(
            model_name='product',
            name='created',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated',
        ),
    ]
