# Generated by Django 3.1.1 on 2021-06-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_auto_20210622_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sell',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
