# Generated by Django 3.1.1 on 2021-06-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_product_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='files/image_product/%Y-%m-%d'),
        ),
    ]
