# Generated by Django 3.1.1 on 2021-06-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_auto_20210623_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='Product.Category'),
        ),
    ]
