# Generated by Django 3.1.1 on 2021-06-24 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_auto_20210623_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
